# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

# The Minecraft version must agree with the NeoForge version to get a valid artifact
minecraft_version=1.21.1
# The Minecraft version range can use any release version of Minecraft as bounds.
minecraft_version_range=[1.21.1,1.22)

# The NeoForge version must agree with the Minecraft version to get a valid artifact
neo_version=21.1.215
# The NeoForge version range
neo_version_range=[21.1,)

# The loader version range can only use the major version of NeoForge/FML as bounds
loader_version_range=[4,)

# Parchment mappings version
parchment_mappings_version=2024.11.17
parchment_minecraft_version=1.21.1

## Mod Properties

# The unique mod identifier. Must be lowercase and match regex [a-z][a-z0-9_]{1,63}
# Must match the String constant in the @Mod annotation of the main mod class.
mod_id=millenaire_rewrite
# The human-readable display name for the mod.
mod_name=Millenaire Rewrite
# The license of the mod.
mod_license=MIT
# The mod version. See https://semver.org/
mod_version=0.2.0-alpha
# The group ID for the mod. Should match the base package used by the mod source code.
mod_group_id=com.jasoncian.millenaire_rewrite
# The authors of the mod.
mod_authors=JasonCian, gblfxt
# The description of the mod.
mod_description=Millenaire mod rewrite for NeoForge 1.21.1 - Living villages with unique cultures that grow and evolve.
